### PR TITLE
feat(): add ability to deserialize stl to csg

### PR DESCRIPTION
**Pull request by kaosat-dev**
This pr adds ability to deserialize stl data to CSG objects directly, and adds unit tests

### CODE REVIEW

**Comment by z3dev** [comment]
openscad.org has some STL files for testing as well. You might want to grab a few of those.

**Comment by kaosat-dev** [comment]
@z3dev  I already added stl files to sample-files, no need for a ton, there aren't that many variations in STL

**Comment by z3dev** [comment]
Hmmm... I don't see a test for STL colors, which I added about 1 year back. Tinkercad produces STL files with colors. See examples/feathers_mcgraw.stl

**Comment by kaosat-dev** [comment]
damn, did not see your comment on time, sorry, will add tests for that later (although my point about not supporting non standard features for stl still stands)

**Pull request merged**
