### PR TITLE
ONML Version of svg serializer

### PR DESCRIPTION
**Pull request by drom**
Clean PR identical to https://github.com/jscad/io/pull/39

### CODE REVIEW

**Comment by kaosat-dev** [comment]
Thanks for this , much appreciated ! 
Very important question : do you know if onml works nicely when browserified and in a web worker ?

**Comment by drom** [comment]
Yes, I am testing ONML in node 0.10 ... 8.7.0 and browser (Firefox, Chrome).

**Comment by kaosat-dev** [comment]
ok cool. and web workers ? 
I will take this for a live spin before we can merge ok ?  :)

**Comment by drom** [comment]
@kaosat-dev yes, workers should be fine.
Do you use browserify?
If yes, I can require ONML differently to include only `stringify` portion of the code, that will give smaller bundle.

**Comment by z3dev** [comment]
Cool! Thanks again, @drom

**Comment by kaosat-dev** [comment]
Yep , browserify for the main ui @drom  thanks for the change!
I am finally less swamped with work, so I can give this a closer look, sorry for the delay

**Comment by z3dev** [comment]
@drom We both like the improvement and the OMNL library, as XML should be avoided at all costs.

However, we don't have any tests. Are you interested in owning this library, and improving both the library and test cases? It shouldn't be hard, but we might ask for some changes.

**Comment by drom** [comment]
@z3dev If you mean ONML library, then I already own it. https://github.com/drom/onml
I have tests, code coverage, run it in production and know several other users of it.
And of cause you can always ask for changes of send me a pull request.

**Comment by z3dev** [comment]
@drom I never doubted. The ONML library looks very nice indeed.

I was hoping that you would like a small piece of the IO library. 😬

**Comment by drom** [comment]
@z3dev I would love to help. Being honest I am a newbie in the world of 3D and constructive solid geometry. I do have understanding of SVG, JS ecosystem and testing. I would need to learn more about capabilities that implemented / planed for IO library. For example: How primitives of one file format should be mapped back and forth into CSG primitives? or How 3D objects should be mapped back into 2D formats like SVG?

**Comment by z3dev** [comment]
Totally understood. I think both @kaosat-dev and I both consider ourselves novices. But learning fast because of the issues in the CSG library.

The whole 2D objectss, API, functions, etc is also creaking. Lots of potential but too few hands

 For example, support for lines is critical for CNC users. That doesn't even exist today.

**Comment by z3dev** [comment]
My account on Hangouts is the same as the Google+ group.

**Comment by drom** [comment]
@z3dev I can't find `OpenJSCAD` user on hangouts

**Comment by z3dev** [comment]
I don't think we have a groups setup. You can chat with me via jeff.gay@z3d.jp

**Comment by z3dev** [comment]
@drom It was good chatting with you. Can you resolve the conflicts with this PR, then I'll merge.

@kaosat-dev Do you have any comments or questions?

**Comment by kaosat-dev** [comment]
@drom would you be ok with updating this PR to solve the issues so that we can (finaly :) ) merge this ?

**Comment by z3dev** [comment]
@kaosat-dev Please do a final review, squash, and merge for release.

@drom Thanks

**Comment by kaosat-dev** [comment]
Looks good to me @drom  , thanks for the changes! 
@z3dev merging !
Side note :  I just saw we have a ton of 'vars' lying around instead of consts/lets , perhaps we should lint those in the future ?
Not your fault at all @drom  I am merging regardless ;)

**Pull request merged**
