### PR TITLE
Onml svg serializer

### PR DESCRIPTION
**Pull request by drom**
Rewrite using ONML library

### CODE REVIEW

**Comment by z3dev** [comment]
@drom I like this... The code is so much easy to maintain without all those "fake' XML tags.

Let's get a review from @kaosat-dev

**Comment by kaosat-dev** [comment]
I like the synax , very declarative, I will do a full review later but it looks good !
A few notes :
- please keep your PRs clean and seperate, I can see the commit for your other PR in there ;-) 
- before we can merge this we need to create the unit tests: changing implementation before knowing if/what breaks is iffy ;-)

**Comment by drom** [comment]
@kaosat-dev Totally agree.
I have aggregated pull request by mistake (in hurry) and I have cleaned it with later commits.
This PR contains only ONML proposal over svg-serializer.
I have included single test for `path`
New `svg-serializer`code has the same limited functionality as original and met to demonstrate ONML integration aspects only.

**Comment by drom** [comment]
Created clean version of PR in #41

**Pull request closed without merging**
