### PR TITLE
fix(svg deserializer): fixed svg-deserializer to work with inkscape file

### PR DESCRIPTION
**Pull request by kaosat-dev**

### CODE REVIEW

**Comment by kaosat-dev** [comment]
Hi @pentacular !
I created this PR based on yours with just a few minor tweaks for it to work as expected. Are you ok with it ?

**Comment by pentacular** [comment]
Sounds good, although might want to distinguish the simple and nested hole cases.

**Comment by z3dev** [comment]
@pentacular 
Once again, thanks for the enhancements. Good stuff. Keep those ideas and fixes coming!

**Comment by kaosat-dev** [comment]
@pentacular fair point , updated

**Pull request merged**
