### PR TITLE
test(): Svg deserializer testing

### PR DESCRIPTION
**Pull request by kaosat-dev**
**WORK IN PROGRESS DO NOT MERGE**

This PR adds tests for the SVG deserializer (also as a basis for future tests of other packages in this repository)

### CODE REVIEW

**Comment by kaosat-dev** [comment]
hi @z3dev thanks for the sample files, but to be honest that is way too large and way too many (GH says 150 ?) , I'll try to take a detailed look at them and make a selection/ filter out based on size and mostly on what openjscad can actually handle :)
I still need to figure out the correct tooling / testing for this repo first I think (Ie I might create another PR that we need to merge before this one), stay tuned !

**Comment by z3dev** [comment]
Yup. A few too many. The openjscad/test* files are probably a good place to start. When developing the library, I tested against the W3 set of svg test files and examples, and expanded to include SVG files created by Fabric (One of my favorite JS libraries.)

**Comment by kaosat-dev** [comment]
Sorry, did not have much time to work on things, however it just hit me : on some other project we also had problems with large sample files, and we simply put those into a separate repository ! This way it can not-included for production version !

**Comment by z3dev** [comment]
Sorry. I don't understand the last comment. The contents of the "package" are controlled by the package.json, so how would samples become part of the "package"?

**Comment by kaosat-dev** [comment]
the package.json just adds metadata, we can just have a git repostiory with some basic metadata that is only used to store the test files : similarly to this one : https://github.com/LaserWeb/lw-sample-files

**Comment by z3dev** [comment]
Look what I found,,,,,

https://github.com/openscad/openscad/tree/master/testdata

**Comment by z3dev** [comment]
Let's make a new repo for the test data, samples, etc.

**Comment by kaosat-dev** [comment]
This PR is obsolete, see #25  for an up to date PR for the svg deserializer, closing

**Pull request closed without merging**
