### PR TITLE
feat(csg output): add basic test & csg output capabilities to deserializers

### PR DESCRIPTION
**Pull request by kaosat-dev**
- [x] amf deserializer
- [x] obj deserializer
- [x] gcode deserializer (needed ?)

### CODE REVIEW

**Comment by z3dev** [comment]
Ummm... GCODE... why bother? It really doesn't work.

**Comment by kaosat-dev** [comment]
sigh, yeah I noticed while adding the tests : should we discard it completely or just leave it there if somebody ever wants to create a working one ?

**Comment by z3dev** [comment]
I really think GCODE should be dropped. The current implementation is really slow and incomplete.

**Comment by kaosat-dev** [comment]
@z3dev I marked the gcode stuff as 'failing' so that there are tests and some code, so if someone wants to add the code down the line, they can

**Pull request merged**
