### PR TITLE
added node v9

### PR DESCRIPTION
**Pull request by drom**

### CODE REVIEW

**Comment by kaosat-dev** [comment]
I am a bit torn on this: v9 is barely a day old or so ... supporting LTS versions of node is one thing, the inbetween ones , perhaps not so much.

**Comment by z3dev** [comment]
@drom Are you willing to try all the libraries with V9?
It would help @kaosat-dev sleep at night. :)

**Comment by drom** [comment]
@z3dev Yes, did run `npm test` on node v9.0.0 all pass.
@kaosat-dev Node v9 is the main stable version now. Next LTS would be v10, not very soon.
Adding v9 as pert of regression helps avoiding compatibility issues moving forward. IMHO

**Comment by z3dev** [comment]
Totally agree. Thanks again.

**Comment by kaosat-dev** [comment]
Ok , let's give it a chance then, thanks @drom :)

**Pull request merged**
